---

- name: install some small, awesome packages to boost your life
  apt: name={{item}} state=present
  with_items:
    - autoconf
    - aptitude
    - cloc
    - curl
    - htop
    - make
    - pinfo
    - proxychains
    - ranger
    - rlwrap
    - texinfo
    - tig
    - tmux
    - editorconfig

# zsh and oh-my-zsh
- name: install zsh
  apt: name={{item}} state=present
  with_items:
    - zsh
    - zsh-lovers
